version: '3.7'

services:

  zookeeper:
    image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
      ]
    ports:
    - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  ibmmq:
    environment:
      LICENSE: accept
      MQ_APP_PASSWORD: passw0rd
      MQ_ENABLE_METRICS: "true"
      MQ_QMGR_NAME: QM1
    image: "quay.io/ibmcase/ibm-mqadvanced-server-dev:9.2.4.0-amd64"
    ports:
      - "1414:1414"
      - "9443:9443"
      - "5672:5672"
    restart: always
    stdin_open: true
    tty: true
  orderms:
    environment:
      FREEZER_REQUEST_QUEUE: DEV.FREEZER_REQUESTS
      FREEZER_RESPONSE_QUEUE: DEV.FREEZER_RESPONSES
      MQ_URL: "failover:(amqp://host.docker.internal:5672?jms.prefetchPolicy.queuePrefetch=1)"
      VOYAGE_REQUEST_QUEUE: DEV.VOYAGE_REQUEST
      VOYAGE_RESPONSE_QUEUE: DEV.VOYAGE_RESPONSE
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    image: "quay.io/ibmcase/eda-kc-order-ms-mq"
    depends_on:
      - "ibmmq"
    ports:
      - "8080:8080"
  reeferms:
    environment:
      FREEZER_REQUEST_QUEUE: DEV.FREEZER_REQUESTS
      FREEZER_RESPONSE_QUEUE: DEV.FREEZER_RESPONSES
      MQ_URL: "failover:(amqp://host.docker.internal:5672?jms.prefetchPolicy.queuePrefetch=1)"
      VOYAGE_REQUEST_QUEUE: DEV.VOYAGE_REQUEST
      VOYAGE_RESPONSE_QUEUE: DEV.VOYAGE_RESPONSE
    image: "quay.io/ibmcase/eda-kc-reefer-mq:1.0-distroless"
    depends_on:
      - "ibmmq"
    ports:
      - "8083:8083"
  voyagems:
    environment:
      FREEZER_REQUEST_QUEUE: DEV.FREEZER_REQUESTS
      FREEZER_RESPONSE_QUEUE: DEV.FREEZER_RESPONSES
      MQ_URL: "failover:(amqp://host.docker.internal:5672?jms.prefetchPolicy.queuePrefetch=1)"
      VOYAGE_REQUEST_QUEUE: DEV.VOYAGE_REQUEST
      VOYAGE_RESPONSE_QUEUE: DEV.VOYAGE_RESPONSE
    image: "quay.io/ibmcase/eda-kc-voyage-ms-mq:1.2-distroless"
    depends_on:
      - "ibmmq"
    ports:
      - "8081:8081"
  web:
   environment:
    API_HOST_ORDERMS=http://host.docker.internal
    API_PORT_ORDERMS=8080
    API_HOST_VOYAGESMS=http://host.docker.internal
    API_PORT_VOYAGESMS=8081
   image: "quay.io/kbilquees/eda-kc-order-mq-ui-main_web"
   stdin_open: true
   tty: true
   ports:
      - "8089:8080"
